language: node_js
node_js: '0.10'

before_install:
  - npm install -g wiredeps@0.2
  - wiredeps --default-branch=master --branch=$TRAVIS_BRANCH --tag=$TRAVIS_TAG --verbose

sudo: false

script: npm run all
